UnicornStore/src/UnicornStore/Controllers/CartController.cs
using System;
using System.Linq;
using System.Security.Claims;
using Microsoft.AspNet.Authorization;
using Microsoft.AspNet.Mvc;
using Microsoft.Data.Entity;
using UnicornStore.AspNet.Models;
using UnicornStore.AspNet.Models.Identity;
using UnicornStore.AspNet.Models.UnicornStore;
using UnicornStore.AspNet.ViewModels.Cart;

namespace UnicornStore.AspNet.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        private UnicornStoreContext db;
        private ApplicationDbContext identityDb;
        CategoryCache categoryCache;

        public CartController(UnicornStoreContext context, ApplicationDbContext identityContext, CategoryCache cache)
        {
            db = context;
            identityDb = identityContext;
            categoryCache = cache;
        }

        public IActionResult Index(IndexMessage message = IndexMessage.None)
        {
            var items = db.CartItems
                .Where(i => i.Username == User.GetUserName())
                .Include(i => i.Product)
                .ToList();

            return View(new IndexViewModel
            {
                CartItems = items,
                TopLevelCategories = categoryCache.TopLevel(),
                Message = message
            });
        }

        public IActionResult Add(int productId, int quantity = 1)
        {
            var product = db.Products
                .SingleOrDefault(p => p.ProductId == productId);

            if (product == null)
            {
                return new HttpStatusCodeResult(404);
            }

            var item = db.CartItems
                .SingleOrDefault(i => i.ProductId == product.ProductId
                                      && i.Username == User.GetUserName());

            if (item != null)
            {
                item.Quantity += quantity;
                item.PricePerUnit = product.CurrentPrice;
                item.PriceCalculated = DateTime.Now.ToUniversalTime();
            }
            else
            {
                item = new CartItem
                {
                    ProductId = product.ProductId,
                    PricePerUnit = product.CurrentPrice,
                    Quantity = quantity,
                    Username = User.GetUserName(),
                    PriceCalculated = DateTime.Now.ToUniversalTime()
                };
                db.CartItems.Add(item);
            }

            db.SaveChanges();

            return RedirectToAction("Index", new { message = IndexMessage.ItemAdded });
        }

        public IActionResult Remove(int productId)
        {
            var item = db.CartItems
                .SingleOrDefault(i => i.ProductId == productId
                                      && i.Username == User.GetUserName());

            if (item == null)
            {
                return new HttpStatusCodeResult(404);
            }

            db.CartItems.Remove(item);
            db.SaveChanges();

            return RedirectToAction("Index", new { message = IndexMessage.ItemRemoved });
        }

        public IActionResult Checkout()
        {
            var items = db.CartItems
                .Where(i => i.Username == User.GetUserName())
                .Include(i => i.Product)
                .ToList();

            var order = new Order
            {
                CheckoutBegan = DateTime.Now.ToUniversalTime(),
                Username = User.GetUserName(),
                Total = items.Sum(i => i.PricePerUnit * i.Quantity),
                State = OrderState.CheckingOut,
                Lines = items.Select(i => new OrderLine
                {
                    ProductId = i.ProductId,
                    Product = i.Product,
                    Quantity = i.Quantity,
                    PricePerUnit = i.PricePerUnit,
                }).ToList()
            };

            db.ChangeTracker.TrackGraph(order, e => e.State = EntityState.Added);
            db.SaveChanges();

            // TODO workaround for https://github.com/aspnet/EntityFramework/issues/1449
            var orderFixed = db.Orders
                .AsNoTracking()
                .Include(o => o.Lines).ThenInclude(ol => ol.Product)
                .Single(o => o.OrderId == order.OrderId);

            orderFixed.ShippingDetails = new OrderShippingDetails();

            var addresses = identityDb.UserAddresses
                .Where(a => a.UserId == User.GetUserId())
                .ToList();

            return View(new CheckoutViewModel
            {
                Order = orderFixed,
                UserAddresses = addresses
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Checkout(CheckoutViewModel formOrder)
        {
            var order = db.Orders
                .Include(o => o.Lines)
                .SingleOrDefault(o => o.OrderId == formOrder.Order.OrderId);

            if (order == null)
            {
                return new HttpStatusCodeResult(404);
            }

            if (order.Username != User.GetUserName())
            {
                return new HttpStatusCodeResult(403);
            }

            if (order.State != OrderState.CheckingOut)
            {
                return new HttpStatusCodeResult(400);
            }

            // Place order
            order.ShippingDetails = formOrder.Order.ShippingDetails.CloneTo<OrderShippingDetails>();
            order.State = OrderState.Placed;
            order.OrderPlaced = DateTime.Now.ToUniversalTime();
            db.SaveChanges();

            if(formOrder.RememberAddress)
            {
                var address = formOrder.Order.ShippingDetails.CloneTo<UserAddress>();
                address.UserId = User.GetUserId();
                identityDb.UserAddresses.Add(address);
                identityDb.SaveChanges();
            }

            // Remove items from cart
            var cartItems = db.CartItems
                .Where(i => i.Username == User.GetUserName())
                .ToList();

            foreach (var item in cartItems)
            {
                if (order.Lines.Any(l => l.ProductId == item.ProductId))
                {
                    db.CartItems.Remove(item);
                }
            }

            db.SaveChanges();

            return RedirectToAction("Details", "Orders", new { orderId = order.OrderId, showConfirmation = true });
        }
    }
}

UnicornStore/src/UnicornStore/Controllers/ManageProductsController.cs
using System.Linq;
using Microsoft.AspNet.Authorization;
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Mvc.Rendering;
using Microsoft.Data.Entity;
using UnicornStore.AspNet.Models.UnicornStore;
using UnicornStore.AspNet.ViewModels.ManageProducts;

namespace UnicornStore.AspNet.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ManageProductsController : Controller
    {
        private UnicornStoreContext db;
        CategoryCache categoryCache;

        public ManageProductsController(UnicornStoreContext context, CategoryCache cache)
        {
            db = context;
            categoryCache = cache;
        }

        // GET: Products
        public IActionResult Index(int? categoryId)
        {
            if (categoryId != null)
            {
                var ids = categoryCache.GetThisAndChildIds(categoryId.Value);
                return View(db.Products.Where(p => ids.Contains(p.CategoryId)));
            }

            return View(db.Products.ToList());
        }

        // GET: Products/Details/5
        public IActionResult Details(System.Int32? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(404);
            }

            Product product = db.Products.Single(m => m.ProductId == id);
            if (product == null)
            {
                return new HttpStatusCodeResult(404);
            }

            return View(product);
        }

        // GET: Products/Create
        public IActionResult Create()
        {
            ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "DisplayName");
            return View();
        }

        // POST: Products/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Product product)
        {
            if (ModelState.IsValid)
            {
                db.Products.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(product);
        }

        // GET: Products/Edit/5
        public IActionResult Edit(System.Int32? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(404);
            }

            Product product = db.Products.Single(m => m.ProductId == id);
            if (product == null)
            {
                return new HttpStatusCodeResult(404);
            }

            ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "DisplayName", product.CategoryId);
            return View(product);
        }

        // POST: Products/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Product product)
        {
            if (ModelState.IsValid)
            {
                db.Update(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(product);
        }

        // GET: Products/Delete/5
        [ActionName("Delete")]
        public IActionResult Delete(System.Int32? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(404);
            }

            Product product = db.Products.Single(m => m.ProductId == id);
            if (product == null)
            {
                return new HttpStatusCodeResult(404);
            }

            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(System.Int32 id)
        {
            Product product = db.Products.Single(m => m.ProductId == id);
            db.Products.Remove(product);
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        public IActionResult BulkPriceReduction()
        {
            ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "DisplayName");
            return View(new BulkPriceReductionViewModel { PercentageOffMSRP = 10 });
        }

        // POST: Products/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult BulkPriceReduction(BulkPriceReductionViewModel model)
        {
            if (ModelState.IsValid)
            {
                var ids = categoryCache.GetThisAndChildIds(model.CategoryId);
                var products = db.Products.Where(p => ids.Contains(p.CategoryId));

                foreach (var product in products)
                {
                    var discount = product.MSRP * model.PercentageOffMSRP / 100;
                    product.CurrentPrice = product.MSRP - discount;
                }

                db.SaveChanges();

                return RedirectToAction("Index", new { categoryId = model.CategoryId });
            }

            return View(model);
        }
    }
}

UnicornStore/src/UnicornStore/Controllers/ShopController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNet.Authorization;
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Mvc.Rendering;
using Microsoft.Data.Entity;
using UnicornStore.AspNet.Models.UnicornStore;
using UnicornStore.AspNet.ViewModels.Shop;

namespace UnicornStore.AspNet.Controllers
{
    public class ShopController : Controller
    {
        private UnicornStoreContext db;
        CategoryCache categoryCache;

        public ShopController(UnicornStoreContext context, CategoryCache cache)
        {
            db = context;
            categoryCache = cache;
        }

        public IActionResult Index()
        {
            // TODO ToList() is a workaround for:
            //        - https://github.com/aspnet/EntityFramework/issues/1851
            //        - https://github.com/aspnet/EntityFramework/issues/1852

            var products = db.Products
                .ToList()
                .OrderByDescending(p => p.MSRP - p.CurrentPrice)
                .Take(4);

            return View(new IndexViewModel
            {
                FeaturedProducts = products,
                TopLevelCategories = categoryCache.TopLevel()
            });
        }

        public IActionResult Category(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(404);
            }

            var category = categoryCache.FromKey(id.Value);

            if (category == null)
            {
                return new HttpStatusCodeResult(404);
            }

            var ids = categoryCache.GetThisAndChildIds(id.Value);
            return View(new CategoryViewModel
            {
                Category = category,
                Products = db.Products.Where(p => ids.Contains(p.CategoryId)),
                ParentHierarchy = categoryCache.GetHierarchy(category.CategoryId),
                Children = category.Children
            });
        }

        public IActionResult Product(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(404);
            }

            var product = db.Products
                .Include(p => p.Category)
                .SingleOrDefault(m => m.ProductId == id);

            if (product == null)
            {
                return new HttpStatusCodeResult(404);
            }

            return View(new ProductViewModel
            {
                Product = product,
                CategoryHierarchy = categoryCache.GetHierarchy(product.CategoryId),
                TopLevelCategories = categoryCache.TopLevel()
            });
        }

        public IActionResult Search(string term)
        {
            var products = db.Products
                .FromSql("SELECT * FROM [dbo].[SearchProducts] (@p0)", term)
                .OrderByDescending(p => p.Savings)
                .ToList();

            return View(new SearchViewModel
            {
                SearchTerm = term,
                Products = products
            });
        }
    }
}

UnicornStore/src/UnicornStore/Views/Shared/_CategorySidebar.cshtml
@model IEnumerable<UnicornStore.AspNet.Models.UnicornStore.Category>

<div class="well">
    <h4>Departments</h4>
    @foreach (var item in Model)
    {
        <p>
            <strong>@Html.ActionLink(item.DisplayName, "Category", "Shop", new { id = item.CategoryId })</strong>
            @if (item.Children.Any())
            {
                @foreach (var child in item.Children)
                {
                    <br />
                    <em>
                        @Html.ActionLink(child.DisplayName, "Category", "Shop", new { id = child.CategoryId })
                    </em>
                }
            }
        </p>
    }
</div>








UnicornStore/src/UnicornStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewBag.Title - Unicorn Store</title>

        <environment names="Development">
            <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.css" />
            <link rel="stylesheet" href="~/lib/bootstrap-touch-carousel/css/bootstrap-touch-carousel.css" />
            <link rel="stylesheet" href="~/css/site.css" />
        </environment>
        <environment names="Staging,Production">
            <link rel="stylesheet" href="//ajax.aspnetcdn.com/ajax/bootstrap/3.0.0/css/bootstrap.min.css"
                  asp-fallback-href="~/lib/bootstrap/css/bootstrap.min.css"
                  asp-fallback-test-class="hidden" asp-fallback-test-property="visibility" asp-fallback-test-value="hidden" />
            <link rel="stylesheet" href="//ajax.aspnetcdn.com/ajax/bootstrap-touch-carousel/0.8.0/css/bootstrap-touch-carousel.css"
                  asp-fallback-href="~/lib/bootstrap-touch-carousel/css/bootstrap-touch-carousel.css"
                  asp-fallback-test-class="carousel-caption" asp-fallback-test-property="display" asp-fallback-test-value="none" />
            <link rel="stylesheet" href="~/css/site.css" />
        </environment>
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a asp-controller="Home" asp-action="Index" class="navbar-brand">Unicorn Store</a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("Browse Store", "Index", "Shop")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                        @if (User.IsInRole(UnicornStore.AspNet.Models.Identity.Roles.Admin))
                        {
                            <li class="dropdown">
                                <a class="dropdown-toggle" role="button" aria-expanded="false" href="#" data-toggle="dropdown">Admin <span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li>@Html.ActionLink("Manage Products", "Index", "ManageProducts")</li>
                                    <li>@Html.ActionLink("Bulk Price Reduction", "BulkPriceReduction", "ManageProducts")</li>
                                </ul>
                            </li>
                        }
                    </ul>
                    <form id="searchForm" class="navbar-form navbar-left" role="search">
                        <div class="form-group">
                            <input id="searchTerm" class="form-control" type="text" placeholder="Search" >
                        </div>
                        <button class="btn btn-default" type="submit">Go</button>
                    </form>
                    
                    @await Html.PartialAsync("_LoginPartial")
                </div>
            </div>
        </div>
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; 2015 - Unicorn Store</p>
            </footer>
        </div>

        <environment names="Development">
            <script src="~/lib/jquery/jquery.js"></script>
            <script src="~/lib/bootstrap/js/bootstrap.js"></script>
            <script src="~/lib/hammer.js/hammer.js"></script>
            <script src="~/lib/bootstrap-touch-carousel/js/bootstrap-touch-carousel.js"></script>
        </environment>
        <environment names="Staging,Production">
            <script src="//ajax.aspnetcdn.com/ajax/jquery/jquery-1.10.2.min.js"
                    asp-fallback-src="~/lib/jquery/jquery.min.js"
                    asp-fallback-test="window.jQuery">
            </script>
            <script src="//ajax.aspnetcdn.com/ajax/bootstrap/3.0.0/bootstrap.min.js"
                    asp-fallback-src="~/lib/bootstrap/js/bootstrap.min.js"
                    asp-fallback-test="window.jQuery">
            </script>
            <script src="//ajax.aspnetcdn.com/ajax/hammer.js/2.0.4/hammer.min.js"
                    asp-fallback-src="~/lib/hammer.js/hammer.js"
                    asp-fallback-test="window.Hammer">
            </script>
            <script src="//ajax.aspnetcdn.com/ajax/bootstrap-touch-carousel/0.8.0/js/bootstrap-touch-carousel.js"
                    asp-fallback-src="~/lib/bootstrap-touch-carousel/js/bootstrap-touch-carousel.js"
                    asp-fallback-test="window.Zepto">
            </script>
        </environment>
        <script>
            $(document).ready(function () {
                $('#searchForm').submit(function (event) {
                    var url = '@Url.Action("Search","Shop")?term=' + $('#searchTerm').val()
                    window.location.href = url;
                    return false;
                });
            })
        </script>
        @RenderSection("scripts", required: false)
    </body>
</html>

UnicornStore/src/UnicornStore/Views/Shared/_LineItem.cshtml
@model UnicornStore.AspNet.Models.UnicornStore.ILineItem

<div class="row">
    <div class="col-md-2">
        <img src="@Url.Content(Model.Product.ImageUrl)" width="100" />
    </div>
    <div class="col-md-9">
        <h4>@Html.ActionLink(Model.Product.DisplayName, "Product", "Shop", new { id = Model.Product.ProductId })</h4>
        <p>
            @Model.Quantity @@ $@Model.PricePerUnit
            <br />
            <span style="font-size: large;">$@(Model.Quantity * Model.PricePerUnit)</span>
        </p>
    </div>
</div>



UnicornStore/src/UnicornStore/Views/Shared/_ProductCard.cshtml
@model UnicornStore.AspNet.Models.UnicornStore.Product

<div class="panel panel-default" >
    <div class="panel-body" style="height: 350px">
        <div style="text-align: center;">
            <p title="@Model.DisplayName">
                @Html.ActionLink(Model.DisplayName, "Product", "Shop", new { id = Model.ProductId })
            </p>
            @if (Model.CurrentPrice == Model.MSRP)
            {
                <p>
                    <span style="font-size: large">$@Model.CurrentPrice</span>
                    <br />
                    <br />
                </p>
            }
            else
            {
                <p>
                    <span class="text-success" style="font-size: large">$@Model.CurrentPrice</span><br />
                    <span class="text-danger"><del>$@Model.MSRP</del></span>
                    (save $@(Model.MSRP - Model.CurrentPrice))
                </p>
            }
            <img src="@Url.Content(Model.ImageUrl)" width="120" />
            <p>@Html.DisplayFor(modelItem => modelItem.Description)</p>
           
        </div>
    </div>
    <div class="panel-footer">
        @Html.ActionLink("Add to Cart", "Add", "Cart", new { productId = Model.ProductId })

    </div>
</div>


